#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    LineR,          sensorLineFollower)
#pragma config(Sensor, in2,    LineC,          sensorLineFollower)
#pragma config(Sensor, in3,    LineL,          sensorLineFollower)
#pragma config(Sensor, in4,    Arm,            sensorPotentiometer)
#pragma config(Sensor, dgtl1,  Son,            sensorSONAR_inch)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           RD,            tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           LD,            tmotorVex393HighSpeed_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           B,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RA,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LA,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(100)
#pragma userControlDuration(100)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "functions.h" //Functions header file

//Pre-Autonomous
void pre_auton()
{
	bStopTasksBetweenModes = true;
}

//Autonomous
task autonomous()
{
}

//User Control
task usercontrol()
{

	while (true)
	{
		{
			//Drive
			motor[LD]  = (vexRT[Ch1] + vexRT[Ch3])/2;  // (y + x)/2
			motor[RD] = (vexRT[Ch1] - vexRT[Ch3])/2;  // (y - x)/2

			//Arm
			if(vexRT[Btn5U] == 1)
			{
				motor[B] = 100;
			}
			else if(vexRT[Btn5D] == 1)
			{
				motor[B] = -100;
			}
			else
			{
				motor[B] = 0;
			}

			//Belt
			if(vexRT[Btn6U] == 1)
			{
				motor[RA] = 60;
				motor[LA] = 60;
			}
			else if(vexRT[Btn6D] == 1)
			{
				motor[RA] = -60;
				motor[LA] = -60;
			}
			else
			{
				motor[RA] = 0;
				motor[LA] = 0;
			}
		}
	}
}
